import { useApp } from '../context/AppContext';
import { useToast } from '../context/ToastContext';
import type { Language, TranslationResult } from '../types';
import { LANGUAGE_LABELS } from '../types';

interface ReportPanelProps {
  sourceCode: string;
  targetCode: string;
  sourceLang: Language;
  targetLang: Language;
  result: TranslationResult | null;
}

export default function ReportPanel({ sourceCode, targetCode, sourceLang, targetLang, result }: ReportPanelProps) {
  const { addToast } = useToast();
  const { history } = useApp();

  const generateMarkdown = () => {
    const date = new Date().toISOString().split('T')[0];
    const srcLabel = LANGUAGE_LABELS[sourceLang];
    const tgtLabel = LANGUAGE_LABELS[targetLang];
    
    return `# Translation Report

**Date:** ${date}
**Source:** ${srcLabel} → **Target:** ${tgtLabel}

---

## Source Code (\`${sourceLang}\`)

\`\`\`${sourceLang}
${sourceCode}
\`\`\`

## Translated Code (\`${targetLang}\`)

\`\`\`${targetLang}
${targetCode}
\`\`\`

## Analysis

${result ? `### Confidence: ${(result.confidence * 100).toFixed(0)}%

${result.comments.length > 0 ? '### Translation Notes\n\n' + result.comments.map(c => `- ${c}`).join('\n') : ''}
` : ''}

## Statistics

- **Source words:** ${sourceCode.trim() ? sourceCode.trim().split(/\s+/).length : 0}
- **Target words:** ${targetCode.trim() ? targetCode.trim().split(/\s+/).length : 0}
- **Source lines:** ${sourceCode.split('\n').length}
- **Target lines:** ${targetCode.split('\n').length}

---

*Generated by Code Translator v2.0*
`;
  };

  const handleCopyMarkdown = async () => {
    const markdown = generateMarkdown();
    try {
      await navigator.clipboard.writeText(markdown);
      addToast('Report copied as Markdown!', 'success');
    } catch {
      addToast('Failed to copy', 'error');
    }
  };

  const handleDownloadMarkdown = () => {
    const markdown = generateMarkdown();
    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `translation-report-${sourceLang}-to-${targetLang}.md`;
    a.click();
    URL.revokeObjectURL(url);
    addToast('Report downloaded!', 'success');
  };

  const handlePrint = () => {
    const markdown = generateMarkdown();
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(`
        <html>
        <head><title>Translation Report</title>
        <style>
          body { font-family: -apple-system, sans-serif; padding: 2rem; color: #1f2328; }
          pre { background: #f6f8fa; padding: 1rem; border-radius: 8px; overflow-x: auto; }
          code { font-family: monospace; }
          h1 { border-bottom: 1px solid #d0d7de; padding-bottom: 0.5rem; }
          h2 { border-bottom: 1px solid #d0d7de; padding-bottom: 0.3rem; margin-top: 2rem; }
          ul { padding-left: 1.5rem; }
        </style>
        </head>
        <body>${markdown
          .replace(/```(\w+)?\n([\s\S]*?)```/g, '<pre><code>$2</code></pre>')
          .replace(/### (.*)/g, '<h3>$1</h3>')
          .replace(/## (.*)/g, '<h2>$1</h2>')
          .replace(/# (.*)/g, '<h1>$1</h1>')
          .replace(/\*\*(.*)\*\*/g, '<strong>$1</strong>')
          .replace(/- (.*)/g, '<li>$1</li>')
          .replace(/\n/g, '<br>')
        }</body>
        </html>
      `);
      printWindow.document.close();
      printWindow.print();
    }
  };

  const hasContent = sourceCode.trim() && targetCode.trim();

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem', height: '100%' }}>
      <div style={{
        padding: '0.75rem', backgroundColor: 'var(--bg-secondary)',
        borderRadius: 'var(--radius-md)', border: '1px solid var(--border)',
      }}>
        <h3 style={{ margin: '0 0 0.5rem 0', fontSize: '0.95rem', fontWeight: 600 }}>📄 Translation Report</h3>
        <p style={{ margin: 0, fontSize: '0.85rem', color: 'var(--text-secondary)' }}>
          Generate a comprehensive Markdown report of your translation including source code, translated code, confidence score, and analysis.
        </p>
      </div>

      {!hasContent ? (
        <div style={{
          flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
          borderRadius: 'var(--radius-md)', border: '2px dashed var(--border)',
          padding: '2rem', textAlign: 'center',
        }}>
          <div style={{ fontSize: '3rem', marginBottom: '1rem' }}>📝</div>
          <div style={{ fontSize: '0.9rem', color: 'var(--text-secondary)' }}>
            Translate some code first to generate a report.
          </div>
        </div>
      ) : (
        <>
          <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap' }}>
            <button onClick={handleCopyMarkdown} style={primaryButtonStyle}>📋 Copy Markdown</button>
            <button onClick={handleDownloadMarkdown} style={secondaryButtonStyle}>⬇ Download .md</button>
            <button onClick={handlePrint} style={secondaryButtonStyle}>🖨 Print</button>
          </div>

          <div style={{
            flex: 1, borderRadius: 'var(--radius-md)', border: '1px solid var(--border)',
            overflow: 'hidden', display: 'flex', flexDirection: 'column', minHeight: 0,
          }}>
            <div style={{
              padding: '0.5rem 0.75rem', backgroundColor: 'var(--bg-secondary)',
              borderBottom: '1px solid var(--border)', fontSize: '0.8rem', color: 'var(--text-secondary)',
              display: 'flex', justifyContent: 'space-between', alignItems: 'center',
            }}>
              <span>Preview</span>
              <span>{sourceLang} → {targetLang}</span>
            </div>
            <div style={{
              flex: 1, overflow: 'auto', padding: '1rem', fontSize: '0.85rem',
              fontFamily: 'var(--font-mono)', whiteSpace: 'pre-wrap', wordBreak: 'break-word',
              backgroundColor: 'var(--bg-primary)', lineHeight: 1.6,
            }}>
              {(() => {
                const md = generateMarkdown();
                return md
                  .replace(/```(\w+)?\n([\s\S]*?)```/g, '\n```\n$2\n```\n')
                  .replace(/### (.*)/g, '\n### $1\n')
                  .replace(/## (.*)/g, '\n## $1\n')
                  .replace(/# (.*)/g, '\n# $1\n')
                  .replace(/\*\*(.*)\*\*/g, '**$1**')
                  .replace(/- (.*)/g, '- $1')
                  .replace(/\n/g, '\n');
              })()}
            </div>
          </div>
        </>
      )}

      {/* Quick stats */}
      {hasContent && (
        <div style={{
          display: 'flex', gap: '1rem', padding: '0.5rem 0.75rem',
          backgroundColor: 'var(--bg-secondary)', borderRadius: 'var(--radius-sm)',
          border: '1px solid var(--border)', fontSize: '0.8rem', color: 'var(--text-secondary)',
        }}>
          <span>📊 {history.length} total translations</span>
          <span>📝 {sourceCode.trim().split(/\s+/).length} source words</span>
          <span>📝 {targetCode.trim().split(/\s+/).length} target words</span>
          {result && <span>🎯 {(result.confidence * 100).toFixed(0)}% confidence</span>}
        </div>
      )}
    </div>
  );
}

const primaryButtonStyle: React.CSSProperties = {
  padding: '0.4rem 0.8rem', backgroundColor: 'var(--accent)', color: 'white', border: 'none',
  borderRadius: 'var(--radius-sm)', cursor: 'pointer', fontSize: '0.8rem', fontWeight: 500,
};

const secondaryButtonStyle: React.CSSProperties = {
  padding: '0.4rem 0.8rem', backgroundColor: 'var(--bg-tertiary)', color: 'var(--text-primary)',
  border: '1px solid var(--border)', borderRadius: 'var(--radius-sm)', cursor: 'pointer', fontSize: '0.8rem',
};
